# Generated by Django 5.2.2 on 2025-06-14 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('fund_manager', 'Fund Manager')], default='user', max_length=20)),
                ('is_contracted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('category_risk_factor', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=6)),
                ('category_time_frame', models.CharField(choices=[('Short Term', 'Short Term'), ('Medium Term', 'Medium Term'), ('Long Term', 'Long Term')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NAVRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TotalCapitalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('total_capital', models.DecimalField(decimal_places=2, max_digits=16)),
                ('invested_capital', models.DecimalField(decimal_places=2, max_digits=16)),
                ('available_capital', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_circulating_unit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserContract',
            fields=[
                ('authorized_user', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contract', serialize=False, to='mainapp.authorizeduser', to_field='email')),
                ('contract_pdf_img', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirmInvestment',
            fields=[
                ('investment_id', models.AutoField(primary_key=True, serialize=False)),
                ('investment_name', models.CharField(max_length=100)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('investment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='mainapp.investmentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='UserBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_number', models.BigIntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('cell_number', models.CharField(max_length=20)),
                ('authorized_user', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='mainapp.authorizeduser', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='UserNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('authorized_user', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='nav', to='mainapp.authorizeduser', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default='Withdrawal', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_initiated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_image', models.ImageField(blank=True, null=True, upload_to='transaction_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_user', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mainapp.authorizeduser', to_field='email')),
            ],
        ),
    ]
