# Generated by Django 5.2.2 on 2025-06-15 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firminvestment',
            name='invested_amount',
        ),
        migrations.RemoveField(
            model_name='firminvestment',
            name='return_amount',
        ),
        migrations.RemoveField(
            model_name='firminvestment',
            name='status',
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_type', models.CharField(choices=[('investment', 'Investment'), ('return', 'Return')], max_length=11)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mainapp.firminvestment')),
            ],
        ),
    ]
