# Generated by Django 5.2.2 on 2025-06-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeduser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('fund_manager', 'Fund Manager')], default='user', max_length=20),
        ),
    ]
