# Generated by Django 5.2.2 on 2025-06-08 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_authorizeduser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_credit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('authorized_user', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='nav', to='mainapp.authorizeduser', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('purchase_nav', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('authorized_user', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mainapp.authorizeduser', to_field='email')),
            ],
        ),
    ]
