# Generated by Django 5.2.2 on 2025-06-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_firminvestment_invested_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firminvestment',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6),
        ),
    ]
