# Generated by Django 5.2.2 on 2025-06-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_usernav_usertransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAVRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
            ],
        ),
    ]
