# Generated by Django 5.2.2 on 2025-06-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_firminvestment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransactionUpload',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_file', models.FileField(blank=True, null=True, upload_to='user_transaction_uploads/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
