# Generated by Django 5.2.2 on 2025-06-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_usertransactionupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontract',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercontract',
            name='recurring_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='usertransactionupload',
            name='is_credited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertransactionupload',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
