# Generated by Django 5.2.2 on 2025-06-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_navrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernav',
            name='available_credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='usernav',
            name='available_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
