# Generated by Django 5.2.2 on 2025-06-17 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_usercontract_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontract',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='usercontract',
            name='recurring_payment_amount',
        ),
        migrations.CreateModel(
            name='UserRecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurring_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('authorized_user', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_payments', to='mainapp.authorizeduser', to_field='email')),
            ],
        ),
    ]
