# Generated by Django 5.2.2 on 2025-06-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_usernav_available_credit_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransaction',
            name='purchase_nav',
        ),
    ]
