# Generated by Django 5.2.2 on 2025-06-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_usertransaction_purchase_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='purchase_initiated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
