# Generated by Django 5.2.2 on 2025-07-06 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Amount requested by user', max_digits=14)),
                ('withdrawal_type', models.CharField(choices=[('partial', 'Partial Withdrawal'), ('full', 'Full Withdrawal'), ('emergency', 'Emergency Withdrawal')], default='partial', max_length=20)),
                ('user_reason', models.TextField(blank=True, help_text="User's reason for withdrawal", null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('available_balance_at_request', models.DecimalField(decimal_places=2, help_text="User's available balance when request was made", max_digits=14)),
                ('available_units_at_request', models.DecimalField(decimal_places=2, help_text="User's available units when request was made", max_digits=12)),
                ('current_nav_at_request', models.DecimalField(decimal_places=2, help_text='NAV value when request was made', max_digits=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved by fund manager (may differ from requested)', max_digits=14, null=True)),
                ('manager_notes', models.TextField(blank=True, help_text="Fund manager's internal notes", null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('processed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('actual_processed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount processed and transferred', max_digits=14, null=True)),
                ('units_redeemed', models.DecimalField(blank=True, decimal_places=2, help_text='Number of units redeemed for this withdrawal', max_digits=12, null=True)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, help_text='Any processing fees deducted', max_digits=8)),
                ('created_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('supporting_documents', models.FileField(blank=True, help_text='Any supporting documents uploaded by user', null=True, upload_to='withdrawal_documents/')),
                ('completion_receipt', models.FileField(blank=True, help_text='Receipt or proof of transfer', null=True, upload_to='withdrawal_receipts/')),
                ('requires_manual_review', models.BooleanField(default=False, help_text='Flag for withdrawals requiring manual review')),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score for this withdrawal (0-100)')),
                ('compliance_checked', models.BooleanField(default=False)),
                ('compliance_notes', models.TextField(blank=True, null=True)),
                ('authorized_user', models.ForeignKey(db_column='user_email', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='mainapp.authorizeduser', to_field='email')),
                ('bank_detail', models.ForeignKey(help_text='Bank account to transfer withdrawal amount', on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='mainapp.userbankdetail')),
            ],
            options={
                'ordering': ['-request_date'],
                'indexes': [models.Index(fields=['status', 'request_date'], name='mainapp_wit_status_420d60_idx'), models.Index(fields=['authorized_user', 'status'], name='mainapp_wit_user_em_c67f64_idx'), models.Index(fields=['priority', 'request_date'], name='mainapp_wit_priorit_8152f1_idx')],
            },
        ),
    ]
