# Generated by Django 5.2.2 on 2025-06-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_usertransaction_purchase_initiated_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default='Withdrawal', max_length=20),
        ),
    ]
