# Generated by Django 5.2.2 on 2025-07-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_withdrawalrequest'),
    ]

    operations = [
    ]
