# Generated by Django 5.2.2 on 2025-06-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_usertransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='transaction_image',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_images/'),
        ),
    ]
