# Generated by Django 5.2.2 on 2025-07-13 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20250713_2333'),
    ]

    operations = [
    ]
