# Generated by Django 5.2.2 on 2025-06-11 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_usertransaction_transaction_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_number', models.BigIntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('cell_number', models.CharField(max_length=20)),
                ('authorized_user', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='mainapp.authorizeduser', to_field='email')),
            ],
        ),
    ]
