# Generated by Django 5.2.2 on 2025-07-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20250713_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='stock_units_purchased',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Units of stock', max_digits=12, null=True),
        ),
    ]
