# Generated by Django 5.2.2 on 2025-06-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_userbankdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
