# Generated by Django 5.2.2 on 2025-06-13 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_usertransaction_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContract',
            fields=[
                ('authorized_user', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contract', serialize=False, to='mainapp.authorizeduser', to_field='email')),
                ('contract_pdf_img', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='authorizeduser',
            name='is_contracted',
            field=models.BooleanField(default=False),
        ),
    ]
