# Generated by Django 5.2.2 on 2025-07-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20250719_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='firminvestment',
            name='share_symbol',
            field=models.CharField(blank=True, help_text='Stock symbol for share market investments (e.g., NABIL, NICA, etc.)', max_length=20, null=True),
        ),
    ]
