# Generated by Django 5.2.2 on 2025-07-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_firminvestment_share_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactionupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usertransactionupload',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
