# Generated by Django 5.2.2 on 2026-03-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_usertransactionupload_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navrecord',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='purchase_unit',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
