# Generated by Django 5.2.2 on 2026-06-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_investmenttransaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttransaction',
            name='amount_type',
            field=models.CharField(choices=[('investment', 'Investment'), ('return', 'Return'), ('interest', 'Interest Income')], max_length=11),
        ),
    ]
